// Generated by rune manifest from board.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { DashboardDto } from "@/src/board/dto/dashboard.ts";
import { ACTIVITY, ISSUES, PROJECT } from "@/src/board/domain/business/board/mod.ts";

// the workspace overview aggregate
export class Dashboard {
  /**
   * @returns the dashboard: stats, recent issues and recent activity
   */
  assemble(): DashboardDto {
    const total = ISSUES.length;
    const done = ISSUES.filter((issue) => issue.status === "done").length;
    const stats = {
      total,
      done,
      completion: total === 0 ? 0 : done / total,
      velocity: PROJECT.velocity,
      budget: 48250,
      trends: [3, 5, 4, 8, 6, 9, 11],
    };
    return {
      project: PROJECT,
      stats,
      issues: ISSUES.slice(0, 3),
      // "recent activity" must be newest-first: sort a copy by the ISO-8601 `at`
      // timestamp descending (don't mutate the shared seed array).
      activitys: [...ACTIVITY].sort((x, y) => y.at.localeCompare(x.at)),
    };
  }
}
