// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.
// Dashboard: the workspace overview aggregate
import { assertEquals } from "#std/assert";
import { Dashboard } from "./mod.ts";

Deno.test("Dashboard.assemble — stats, 3 recent issues, activity feed", () => {
  const dash = new Dashboard().assemble();
  assertEquals(dash.stats.total, 6);
  assertEquals(dash.stats.done, 1);
  assertEquals(dash.stats.completion, 1 / 6); // done / total
  assertEquals(dash.stats.velocity, 34); // from PROJECT
  assertEquals(dash.issues.length, 3); // recent slice
  assertEquals(dash.activitys.length, 5);
});
