// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assert, assertRejects } from "#std/assert";
import { ensure } from "./mod.ts";
import { Runner } from "@/src/testing/domain/data/runner/mod.ts";

Deno.test("ensure — happy path", async () => {
  // Drives the coordinator end-to-end; returns a valid runner status.
  const out = await ensure({ projectRoot: "." });
  assert(typeof out.ok === "boolean");
  assert(typeof out.path === "string");
});

Deno.test("provision-failed", async () => {
  // The fault is raised at the os boundary; assert via the adapter with deps.
  await assertRejects(
    () =>
      new Runner().provision(".", {
        status: () => Promise.reject(new Error("boom")),
      }),
    Error,
    "provision-failed",
  );
});
