// GENERATED by sprig build (dev) — the counter island chunk (fetches its AST).
import { registerIsland, makeClassSetup, fetchAst } from "file:///Users/raphaelcastro/Documents/programming/sprig/framework/.sprig/compiler/hydrate.ts";
import logic from "/Users/raphaelcastro/Documents/programming/sprig/fixtures/sprig-app/src/islands/counter/logic.ts";
const __setup = logic.setup ?? makeClassSetup(logic);
const __cfg = JSON.parse(document.getElementById("__sprig_config")?.textContent ?? "{}");
fetchAst(__cfg.base ?? "/ui", "counter").then((t) =>
  registerIsland("counter", { setup: __setup, template: t, scope: "s75c80e66" }));
