// GENERATED by sprig build (dev) — the greeter island chunk (fetches its AST).
import { registerIsland, makeClassSetup, fetchAst } from "file:///Users/raphaelcastro/Documents/programming/sprig/framework/.sprig/compiler/hydrate.ts";
import logic from "/Users/raphaelcastro/Documents/programming/sprig/fixtures/sprig-app/src/islands/greeter/logic.ts";
const __setup = logic.setup ?? makeClassSetup(logic);
const __cfg = JSON.parse(document.getElementById("__sprig_config")?.textContent ?? "{}");
fetchAst(__cfg.base ?? "/ui", "greeter").then((t) =>
  registerIsland("greeter", { setup: __setup, template: t, scope: "s547be5e0" }));
