// GENERATED by sprig build (dev) — the clock island chunk (fetches its AST).
import { registerIsland, makeClassSetup, fetchAst } from "file:///Users/raphaelcastro/Documents/programming/sprig/framework/.sprig/compiler/hydrate.ts";
import logic from "/Users/raphaelcastro/Documents/programming/sprig/fixtures/sprig-app/src/islands/clock/logic.ts";
const __setup = logic.setup ?? makeClassSetup(logic);
const __cfg = JSON.parse(document.getElementById("__sprig_config")?.textContent ?? "{}");
fetchAst(__cfg.base ?? "/ui", "clock").then((t) =>
  registerIsland("clock", { setup: __setup, template: t, scope: "sb6149bb8" }));
