// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.
//
// End-to-end for the board backend: boots the module in-process and drives every
// endpoint through api.backend.fetch — the exact in-process channel serveSprig and
// the sprig UI's inject(Backend) use (no port, no token). Run: RUNE_E2E=1 deno test -A.

import { httpModule } from "./mod.ts";
import { bootstrapServer, exerciseEndpoints } from "@mrg-keystone/keep";
import { assert, assertEquals } from "#std/assert";

Deno.test({
  name: "board/http — endpoints run, chain, and return correct view-models",
  ignore: !Deno.env.get("RUNE_E2E"),
  fn: async (t) => {
    const api = await bootstrapServer("board", httpModule, { swagger: true });
    const post = (path: string, body: unknown = {}) =>
      api.backend.fetch(path, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      });
    try {
      await t.step("run-all walk: no endpoint fails", async () => {
        const report = await exerciseEndpoints({ api });
        assertEquals(report.failed.map((r) => r.id), []);
        assert(report.passed.length >= 4);
      });

      await t.step("board → project + 5 column groups", async () => {
        const board = await (await post("/http/board")).json();
        assertEquals(board.project.name, "sprig");
        assertEquals(board.groups.length, 5);
        const wip = board.groups.find((g: { column: { id: string } }) => g.column.id === "in-progress");
        assertEquals(wip.issues[0].id, "SPR-101");
      });

      await t.step("dashboard → stats + recent + activity", async () => {
        const dash = await (await post("/http/dashboard")).json();
        assertEquals(dash.stats.total, 6);
        assertEquals(dash.stats.done, 1);
        assertEquals(dash.stats.trends.length, 7);
        assertEquals(dash.issues.length, 3);
        assertEquals(dash.activitys.length, 5);
      });

      await t.step("issue {SPR-101} → issue + assignees + comments + related", async () => {
        const detail = await (await post("/http/issue", { issueId: "SPR-101" })).json();
        assertEquals(detail.issue.id, "SPR-101");
        assertEquals(detail.users.map((u: { id: string }) => u.id), ["ada", "alan"]);
        assertEquals(detail.comments.length, 2);
        assertEquals(detail.relateds.length, 3);
      });

      await t.step("user {ada} → profile + assigned issues", async () => {
        const profile = await (await post("/http/user", { userId: "ada" })).json();
        assertEquals(profile.user.name, "Ada Lovelace");
        assert(profile.issues.every((i: { assignees: string[] }) => i.assignees.includes("ada")));
      });

      await t.step("validation: missing issueId → 422", async () => {
        const res = await post("/http/issue", {});
        assertEquals(res.status, 422);
        await res.body?.cancel();
      });
    } finally {
      await api.stop();
    }
  },
});
