// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/keep";
import { BoardDto } from "@/src/board/dto/board.ts";
import { DashboardDto } from "@/src/board/dto/dashboard.ts";
import { IssueRefDto } from "@/src/board/dto/issue-ref.ts";
import { IssueDetailDto } from "@/src/board/dto/issue-detail.ts";
import { UserRefDto } from "@/src/board/dto/user-ref.ts";
import { UserProfileDto } from "@/src/board/dto/user-profile.ts";
import { get as boardGet } from "@/src/board/domain/coordinators/board-get/mod.ts";
import { get as dashboardGet } from "@/src/board/domain/coordinators/dashboard-get/mod.ts";
import { get as issueGet } from "@/src/board/domain/coordinators/issue-get/mod.ts";
import { get as userGet } from "@/src/board/domain/coordinators/user-get/mod.ts";

@EndpointController("http")
export class HttpController {
  /**
   * Delegates to coordinator board.get (matched by input/output signature).
   * @returns BoardDto — the whole board: a project and its grouped issues
   */
  // from board.rune:23
  @Endpoint({ path: "board", output: BoardDto, order: 1 })
  board(): Promise<BoardDto> {
    return boardGet({});
  }

  /**
   * Delegates to coordinator dashboard.get (matched by input/output signature).
   * @returns DashboardDto — the dashboard: stats, recent issues and recent activity
   */
  // from board.rune:24
  @Endpoint({ path: "dashboard", output: DashboardDto, order: 2 })
  dashboard(): Promise<DashboardDto> {
    return dashboardGet({});
  }

  /**
   * Delegates to coordinator issue.get (matched by input/output signature).
   * @param body IssueRefDto — a reference to one issue by id
   * @returns IssueDetailDto — a full issue page: the issue, assignees, comments and related issues
   */
  // from board.rune:25
  @Endpoint({ path: "issue", input: IssueRefDto, output: IssueDetailDto, order: 3 })
  issue(body: IssueRefDto): Promise<IssueDetailDto> {
    return issueGet(body);
  }

  /**
   * Delegates to coordinator user.get (matched by input/output signature).
   * @param body UserRefDto — a reference to one user by id
   * @returns UserProfileDto — a user profile: the user and their assigned issues
   */
  // from board.rune:26
  @Endpoint({ path: "user", input: UserRefDto, output: UserProfileDto, order: 4 })
  user(body: UserRefDto): Promise<UserProfileDto> {
    return userGet(body);
  }
}

export const httpModule = endpointModule("Board", [HttpController]);
