// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] board.get @ board.rune:7):
//   1. [NEW] board
//   2. board.assemble(): BoardDto
import { assertEquals } from "#std/assert";
import { get } from "./mod.ts";

Deno.test("board.get — returns a BoardDto that passes the output assert seam", async () => {
  const board = await get({});
  assertEquals(board.project.name, "sprig");
  assertEquals(board.groups.length, 5);
});
