// Generated by rune manifest from board.rune:7.
// Edit the body. Re-running manifest will not overwrite this file.

import { BoardDto } from "@/src/board/dto/board.ts";
import { assert } from "#assert";
import { Board } from "@/src/board/domain/business/board/mod.ts";

/**
 * Coordinator for [REQ] board.get({}): BoardDto.
 * @param input {} — passed through unvalidated (no [TYP] contract).
 * @returns BoardDto — asserted before return.
 */
export async function get(input: {}): Promise<BoardDto> {

  // core — pure business logic, no I/O
  const out = getCore(input);

  return assert(BoardDto, out.result, "board.get output");
}

// Pure business logic for board.get — no I/O. Takes the
// request input; returns the result.
function getCore(input: {}): { result: BoardDto } {
  const board = new Board();
  return { result: board.assemble() };
}
