// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] user.get @ board.rune:19):
//   1. [NEW] user
//   2. user.assemble(userId): UserProfileDto
import { assertEquals, assertRejects } from "#std/assert";
import { get } from "./mod.ts";

Deno.test("user.get — a valid ref returns the profile", async () => {
  const profile = await get({ userId: "ada" });
  assertEquals(profile.user.id, "ada");
  assertEquals(profile.issues.length, 2);
});

Deno.test("user.get — invalid input is rejected at the input assert seam (→ 422)", async () => {
  // deno-lint-ignore no-explicit-any
  await assertRejects(() => get({} as any)); // missing userId fails the UserRefDto contract
});
