// Generated by rune manifest from board.rune:19.
// Edit the body. Re-running manifest will not overwrite this file.

import { UserRefDto } from "@/src/board/dto/user-ref.ts";
import { UserProfileDto } from "@/src/board/dto/user-profile.ts";
import { assert, RuneAssertError } from "#assert";
import { User } from "@/src/board/domain/business/user/mod.ts";
import { HttpException } from "jsr:@danet/core@2";

// The strict input contract: only these top-level keys are accepted. Unknown
// keys are rejected at the seam (422) rather than silently stripped/accepted.
const ALLOWED_KEYS = ["userId"];

/**
 * Coordinator for [REQ] user.get(UserRefDto): UserProfileDto.
 * @param input UserRefDto — asserted against its contract at the seam.
 * @returns UserProfileDto — asserted before return.
 */
export async function get(input: UserRefDto): Promise<UserProfileDto> {
  rejectUnknownKeys(input);
  const validInput = assert(UserRefDto, input, "user.get input");

  // core — pure business logic, no I/O
  const out = getCore(validInput);

  return assert(UserProfileDto, out.result, "user.get output");
}

// Reject unknown top-level keys with a 422 RuneAssertError so the input contract
// is strict (unknown fields are not silently accepted).
function rejectUnknownKeys(input: UserRefDto): void {
  if (typeof input !== "object" || input === null || Array.isArray(input)) return;
  const unknown = Object.keys(input).filter((key) => !ALLOWED_KEYS.includes(key));
  if (unknown.length > 0) {
    throw new RuneAssertError(
      "UserRefDto",
      unknown.map((key) => ({
        path: key,
        constraint: "unknownField",
        message: `unexpected field "${key}"`,
      })),
      "user.get input",
    );
  }
}

// Pure business logic for user.get — no I/O. Takes the
// request input; returns the result. A well-formed id that names no user is a
// client addressing error -> 404, not a server fault.
function getCore(input: UserRefDto): { result: UserProfileDto } {
  const user = new User();
  try {
    return { result: user.assemble(input.userId) };
  } catch (e) {
    if (e instanceof HttpException || e instanceof RuneAssertError) throw e;
    throw new HttpException(404, "no such user");
  }
}
