// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assertStrictEquals } from "#std/assert";
import { Test } from "./mod.ts";
import { TestReportDto } from "@/src/testing/dto/test-report.ts";

Deno.test("Test.collect", () => {
  const dto = {
    ok: true,
    ran: false,
    total: 0,
    passed: 0,
    failed: 0,
  } as unknown as TestReportDto;
  // collect is the identity step that returns the runner's report as-is.
  assertStrictEquals(new Test().collect(dto), dto);
});
