// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assert, assertRejects } from "#std/assert";
import { Runner } from "./mod.ts";

Deno.test("runner — connectivity", async () => {
  // provision reaches the os boundary (status check) and returns a valid shape.
  const s = await new Runner().provision(".");
  assert(typeof s.ok === "boolean");
  assert(typeof s.path === "string");
});

Deno.test("runner-unavailable", async () => {
  await assertRejects(
    () =>
      new Runner().run({ projectRoot: "/tmp", files: ["/tmp/a.spec.ts"] }, {
        runnerPresent: () => Promise.resolve(false),
      }),
    Error,
    "runner-unavailable",
  );
});

Deno.test("no-match", async () => {
  // A selector (files) that resolves to zero safe specs raises no-match.
  await assertRejects(
    () => new Runner().run({ projectRoot: "/tmp", files: ["/etc/passwd"] }),
    Error,
    "no-match",
  );
});

Deno.test("timeout", async () => {
  await assertRejects(
    () =>
      new Runner().run({ projectRoot: "/tmp", files: ["/tmp/a.spec.ts"] }, {
        runnerPresent: () => Promise.resolve(true),
        runSpec: () => Promise.reject(new Error("timeout")),
      }),
    Error,
    "timeout",
  );
});

Deno.test("provision-failed", async () => {
  await assertRejects(
    () =>
      new Runner().provision(".", {
        status: () => Promise.reject(new Error("boom")),
      }),
    Error,
    "provision-failed",
  );
});
