// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] dashboard.get @ board.rune:11):
//   1. [NEW] dashboard
//   2. dashboard.assemble(): DashboardDto
import { assertEquals } from "#std/assert";
import { get } from "./mod.ts";

Deno.test("dashboard.get — returns a DashboardDto that passes the output assert seam", async () => {
  const dash = await get({});
  assertEquals(dash.stats.total, 6);
  assertEquals(dash.stats.done, 1);
});
