// Generated by rune manifest from board.rune:11.
// Edit the body. Re-running manifest will not overwrite this file.

import { DashboardDto } from "@/src/board/dto/dashboard.ts";
import { assert } from "#assert";
import { Dashboard } from "@/src/board/domain/business/dashboard/mod.ts";

/**
 * Coordinator for [REQ] dashboard.get({}): DashboardDto.
 * @param input {} — passed through unvalidated (no [TYP] contract).
 * @returns DashboardDto — asserted before return.
 */
export async function get(input: {}): Promise<DashboardDto> {

  // core — pure business logic, no I/O
  const out = getCore(input);

  return assert(DashboardDto, out.result, "dashboard.get output");
}

// Pure business logic for dashboard.get — no I/O. Takes the
// request input; returns the result.
function getCore(input: {}): { result: DashboardDto } {
  const dashboard = new Dashboard();
  return { result: dashboard.assemble() };
}
