// Generated by rune manifest — DO NOT EDIT (regenerated on every `rune sync`).

// Domain nouns (from [NON]):
//   board: the kanban board aggregate
//   dashboard: the workspace overview aggregate
//   issue: a single unit of work
//   user: a workspace member
//
// Type vocabulary (from [TYP]):
//   id: string — a stable identifier
//   key: string — a project key, e.g. SPR
//   name: string — a human-readable name
//   velocity: number — points delivered per sprint
//   label: string — a short display label
//   wip: number — a column work-in-progress limit
//   title: string — an issue title
//   status: string — a workflow status (backlog, todo, in-progress, review, done)
//   priority: string — an issue priority (low, medium, high, urgent)
//   points: number — story points for an issue
//   tone: string — a colour tone name for a tag chip
//   assignee: string — a user id assigned to an issue
//   descriptionHtml: string — trusted, server-authored issue description HTML
//   bodyHtml: string — trusted, server-authored comment body HTML
//   author: string — the user id who wrote a comment
//   at: string — an ISO 8601 timestamp
//   commentCount: number — number of comments on an issue
//   createdAt: string — ISO 8601 creation time
//   updatedAt: string — ISO 8601 last-updated time
//   kind: string — an activity kind (comment, status, assign, create)
//   actor: string — the user id who performed an activity
//   issueId: string — an issue id used to fetch one issue
//   userId: string — a user id used to fetch one profile
//   detail: string — a one-line activity description
//   completion: number — completion ratio from 0 to 1
//   budget: number — remaining budget in the project currency
//   total: number — total number of issues
//   done: number — number of completed issues
//   trend: number — completed points for one day of the trend
//   bio: string — a one-line user biography
//   role: string — a workspace role (owner, maintainer, contributor)
//   color: string — a hex colour for the user avatar
// Public API surface for module "board".

export { get as boardGet } from "./domain/coordinators/board-get/mod.ts";

export { get as dashboardGet } from "./domain/coordinators/dashboard-get/mod.ts";

export { get as issueGet } from "./domain/coordinators/issue-get/mod.ts";

export { get as userGet } from "./domain/coordinators/user-get/mod.ts";

