// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assert, assertEquals, assertRejects } from "#std/assert";
import { scan } from "./mod.ts";
import { Project } from "@/src/discovery/domain/data/project/mod.ts";

Deno.test("scan — happy path", async () => {
  // Drive the whole coordinator (validate -> fs read -> collect -> validate).
  const dir = await Deno.makeTempDir();
  try {
    const out = await scan({ projectRoot: dir });
    assert(Array.isArray(out.entrys));
    assertEquals(out.entrys.length, 0);
    assert(Array.isArray(out.problems));
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("scan-failed", async () => {
  // The fault is raised at the fs boundary; assert via the adapter (the
  // coordinator constructs the adapter internally, so inject deps here).
  await assertRejects(
    () =>
      new Project().scan("/x", {
        discover: () => {
          throw new Error("unreadable");
        },
      }),
    Error,
    "scan-failed",
  );
});
