// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// reuse an already-running preview server
// rune declares: [TYP] baseUrl: string
export type BaseUrl = string;
