// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the case a test result belongs to
// rune declares: [TYP] caseName: string
export type CaseName = string;
