// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// human-readable explanation of a problem
// rune declares: [TYP] detail: string
export type Detail = string;
