// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// error message text
// rune declares: [TYP] error: string
export type Error = string;
