// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// failing test count
// rune declares: [TYP] failed: number
export type Failed = number;
