// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// matches a spec file path OR component/case
// rune declares: [TYP] filter: string
export type Filter = string;
