// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the problem kind (fixture/case/file/export)
// rune declares: [TYP] kind: string
export type Kind = string;
