// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// source line of the test
// rune declares: [TYP] line: number
export type Line = number;
