// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// human-readable runner status detail
// rune declares: [TYP] message: string
export type Message = string;
