// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// passing test count
// rune declares: [TYP] passed: number
export type Passed = number;
