// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a discovery config problem surfaced by a run
export class ProblemDto {
  @IsString()
  kind!: string;

  @IsString()
  path!: string;

  @IsString()
  detail!: string;
}
