// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// host project root; defaults to the server's cwd
// rune declares: [TYP:example=.] projectRoot: string
export type ProjectRoot = string;
