// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// whether the run actually executed
// rune declares: [TYP] ran: boolean
export type Ran = boolean;
