// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the preview route the spec ran against
// rune declares: [TYP] route: string
export type Route = string;
