// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsBoolean, IsOptional, IsString } from "class-validator";

// health of the ~/.isolate-runner Playwright runner
export class RunnerStatusDto {
  @IsBoolean()
  ok!: boolean;

  @IsOptional()
  @IsString()
  version?: string;

  @IsString()
  path!: string;

  @IsOptional()
  @IsString()
  message?: string;
}
