// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// path to a failure screenshot
// rune declares: [TYP] screenshot: string
export type Screenshot = string;
