// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsArray, IsOptional, IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

// selectors for a test run; omit all to run everything
export class TestRunRequestDto {
  @IsOptional()
  @IsString()
  filter?: string;

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  files?: string[];

  @IsOptional()
  @IsString()
  baseUrl?: string;

  @ApiProperty({ example: "." })
  @IsOptional()
  @IsString()
  projectRoot?: string;
}
