// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the test title
// rune declares: [TYP] title: string
export type Title = string;
