// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// total test count
// rune declares: [TYP] total: number
export type Total = number;
