// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the provisioned Playwright version
// rune declares: [TYP] version: string
export type Version = string;
