// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] issue.get @ board.rune:15):
//   1. [NEW] issue
//   2. issue.assemble(issueId): IssueDetailDto
import { assertEquals, assertRejects } from "#std/assert";
import { get } from "./mod.ts";

Deno.test("issue.get — a valid ref returns the issue detail", async () => {
  const detail = await get({ issueId: "SPR-101" });
  assertEquals(detail.issue.id, "SPR-101");
  assertEquals(detail.users.length, 2);
});

Deno.test("issue.get — invalid input is rejected at the input assert seam (→ 422)", async () => {
  // deno-lint-ignore no-explicit-any
  await assertRejects(() => get({} as any)); // missing issueId fails the IssueRefDto contract
});
