// Generated by rune manifest from board.rune:15.
// Edit the body. Re-running manifest will not overwrite this file.

import { IssueRefDto } from "@/src/board/dto/issue-ref.ts";
import { IssueDetailDto } from "@/src/board/dto/issue-detail.ts";
import { assert, RuneAssertError } from "#assert";
import { Issue } from "@/src/board/domain/business/issue/mod.ts";

// The strict input contract: only these top-level keys are accepted. Unknown
// keys are rejected at the seam (422) rather than silently stripped/accepted.
const ALLOWED_KEYS = ["issueId"];

/**
 * Coordinator for [REQ] issue.get(IssueRefDto): IssueDetailDto.
 * @param input IssueRefDto — asserted against its contract at the seam.
 * @returns IssueDetailDto — asserted before return.
 */
export async function get(input: IssueRefDto): Promise<IssueDetailDto> {
  rejectUnknownKeys(input);
  const validInput = assert(IssueRefDto, input, "issue.get input");

  // core — pure business logic, no I/O
  const out = getCore(validInput);

  return assert(IssueDetailDto, out.result, "issue.get output");
}

// Reject unknown top-level keys with a 422 RuneAssertError so the input contract
// is strict (unknown fields are not silently accepted).
function rejectUnknownKeys(input: IssueRefDto): void {
  if (typeof input !== "object" || input === null || Array.isArray(input)) return;
  const unknown = Object.keys(input).filter((key) => !ALLOWED_KEYS.includes(key));
  if (unknown.length > 0) {
    throw new RuneAssertError(
      "IssueRefDto",
      unknown.map((key) => ({
        path: key,
        constraint: "unknownField",
        message: `unexpected field "${key}"`,
      })),
      "issue.get input",
    );
  }
}

// Pure business logic for issue.get — no I/O. Takes the
// request input; returns the result.
function getCore(input: IssueRefDto): { result: IssueDetailDto } {
  const issue = new Issue();
  return { result: issue.assemble(input.issueId) };
}
