// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/keep";
import { TestRunRequestDto } from "@/src/testing/dto/test-run-request.ts";
import { TestReportDto } from "@/src/testing/dto/test-report.ts";
import { RootDto } from "@/src/testing/dto/root.ts";
import { RunnerStatusDto } from "@/src/testing/dto/runner-status.ts";
import { run as testRun } from "@/src/testing/domain/coordinators/test-run/mod.ts";
import { ensure as runnerEnsure } from "@/src/testing/domain/coordinators/runner-ensure/mod.ts";

@EndpointController("http")
export class HttpController {
  @Endpoint({ path: "post-test-run", input: TestRunRequestDto, output: TestReportDto, order: 1 })
  postTestRun(body: TestRunRequestDto): Promise<TestReportDto> {
    return testRun(body);
  }

  @Endpoint({ path: "get-runner-status", input: RootDto, output: RunnerStatusDto, order: 2 })
  getRunnerStatus(body: RootDto): Promise<RunnerStatusDto> {
    return runnerEnsure(body);
  }
}

export const httpModule = endpointModule("Testing", [HttpController]);
