// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/rune";
import { RootDto } from "@/src/discovery/dto/root.ts";
import { DiscoverResultDto } from "@/src/discovery/dto/discover-result.ts";
import { ManifestDto } from "@/src/discovery/dto/manifest.ts";
import { scan as discoveryScan } from "@/src/discovery/domain/coordinators/discovery-scan/mod.ts";
import { build as manifestBuild } from "@/src/discovery/domain/coordinators/manifest-build/mod.ts";

@EndpointController("http")
export class HttpController {
  @Endpoint({ path: "get-discovery", input: RootDto, output: DiscoverResultDto, order: 1 })
  getDiscovery(body: RootDto): Promise<DiscoverResultDto> {
    return discoveryScan(body);
  }

  @Endpoint({ path: "get-manifest", input: RootDto, output: ManifestDto, order: 2 })
  getManifest(body: RootDto): Promise<ManifestDto> {
    return manifestBuild(body);
  }
}

export const httpModule = endpointModule("Discovery", [HttpController]);
