// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assert, assertEquals, assertRejects } from "#std/assert";
import { run } from "./mod.ts";
import { Runner } from "@/src/testing/domain/data/runner/mod.ts";

Deno.test("run — happy path", async () => {
  // No selector + a project with no specs => a valid, empty (green) report.
  const dir = await Deno.makeTempDir();
  try {
    const out = await run({ projectRoot: dir });
    assertEquals(out.ok, true);
    assertEquals(out.ran, false);
    assertEquals(out.total, 0);
    assert(Array.isArray(out.testResults ?? []));
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

// Faults are raised at the os boundary; assert via the adapter with injected
// deps (the coordinator builds the adapter internally).
Deno.test("runner-unavailable", async () => {
  await assertRejects(
    () =>
      new Runner().run({ projectRoot: "/tmp", files: ["/tmp/a.spec.ts"] }, {
        runnerPresent: () => Promise.resolve(false),
      }),
    Error,
    "runner-unavailable",
  );
});

Deno.test("no-match", async () => {
  await assertRejects(
    () => new Runner().run({ projectRoot: "/tmp", files: ["/etc/passwd"] }),
    Error,
    "no-match",
  );
});

Deno.test("timeout", async () => {
  await assertRejects(
    () =>
      new Runner().run({ projectRoot: "/tmp", files: ["/tmp/a.spec.ts"] }, {
        runnerPresent: () => Promise.resolve(true),
        runSpec: () => Promise.reject(new Error("timeout")),
      }),
    Error,
    "timeout",
  );
});
