// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assertStrictEquals } from "#std/assert";
import { Discovery } from "./mod.ts";
import { DiscoverResultDto } from "@/src/discovery/dto/discover-result.ts";

Deno.test("Discovery.collect", () => {
  const dto = { entrys: [], problems: [] } as unknown as DiscoverResultDto;
  // collect is the identity step that returns the scanned result as-is.
  assertStrictEquals(new Discovery().collect(dto), dto);
});
