// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assertStrictEquals, assertThrows } from "#std/assert";
import { Runner } from "./mod.ts";
import { RunnerStatusDto } from "@/src/testing/dto/runner-status.ts";

Deno.test("Runner.run", () => {
  // run/provision on the BUSINESS runner are unused artifacts of the dual-role
  // noun (the os: data adapter owns them); they intentionally throw.
  assertThrows(() => new Runner().run({} as never), Error, "unused");
});

Deno.test("Runner.provision", () => {
  assertThrows(() => new Runner().provision(""), Error, "unused");
});

Deno.test("Runner.collect", () => {
  const dto = { ok: true, path: "/x" } as unknown as RunnerStatusDto;
  assertStrictEquals(new Runner().collect(dto), dto);
});
