// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * one entry in the recent-activity feed
 * @internal
 */
// rune declares: [DTO] ActivityDto: id, kind, actor, issueId, at, detail
export class ActivityDto {
  /** a stable identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a stable identifier" })
  @IsString()
  id!: string;

  /** an activity kind (comment, status, assign, create) */
  // rune declares: [TYP] kind: string
  @ApiProperty({ description: "an activity kind (comment, status, assign, create)" })
  @IsString()
  kind!: string;

  /** the user id who performed an activity */
  // rune declares: [TYP] actor: string
  @ApiProperty({ description: "the user id who performed an activity" })
  @IsString()
  actor!: string;

  /** an issue id used to fetch one issue */
  // rune declares: [TYP:example=SPR-101] issueId: string
  @ApiProperty({ description: "an issue id used to fetch one issue", example: "SPR-101" })
  @IsString()
  issueId!: string;

  /** an ISO 8601 timestamp */
  // rune declares: [TYP] at: string
  @ApiProperty({ description: "an ISO 8601 timestamp" })
  @IsString()
  at!: string;

  /** a one-line activity description */
  // rune declares: [TYP] detail: string
  @ApiProperty({ description: "a one-line activity description" })
  @IsString()
  detail!: string;
}
