// Generated by rune manifest from board.rune:68.
// Edit the body. Re-running manifest will not overwrite this file.

/** the user id who performed an activity */
// rune declares: [TYP] actor: string
export type Actor = string;
