// Generated by rune manifest from board.rune:50.
// Edit the body. Re-running manifest will not overwrite this file.

/** a user id assigned to an issue */
// rune declares: [TYP] assignee: string
export type Assignee = string;
