// Generated by rune manifest from board.rune:58.
// Edit the body. Re-running manifest will not overwrite this file.

/** an ISO 8601 timestamp */
// rune declares: [TYP] at: string
export type At = string;
