// Generated by rune manifest from board.rune:56.
// Edit the body. Re-running manifest will not overwrite this file.

/** the user id who wrote a comment */
// rune declares: [TYP] author: string
export type Author = string;
