// Generated by rune manifest from board.rune:86.
// Edit the body. Re-running manifest will not overwrite this file.

/** a one-line user biography */
// rune declares: [TYP] bio: string
export type Bio = string;
