// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { IsArray, ValidateNested } from "class-validator";
import { GroupDto } from "@/src/board/dto/group.ts";
import { ProjectDto } from "@/src/board/dto/project.ts";

/**
 * the whole board: a project and its grouped issues
 * @internal
 */
// rune declares: [DTO] BoardDto: project, group(s)
export class BoardDto {
  /** the project the board belongs to */
  @ValidateNested()
  @Type(() => ProjectDto)
  project!: ProjectDto;

  /** a column paired with its issues */
  // rune: group(s) — array of [DTO] GroupDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => GroupDto)
  groups!: GroupDto[];
}
