// Generated by rune manifest from board.rune:54.
// Edit the body. Re-running manifest will not overwrite this file.

/** trusted, server-authored comment body HTML */
// rune declares: [TYP] bodyHtml: string
export type BodyHtml = string;
