// Generated by rune manifest from board.rune:78.
// Edit the body. Re-running manifest will not overwrite this file.

/** remaining budget in the project currency */
// rune declares: [TYP] budget: number
export type Budget = number;
