// Generated by rune manifest from board.rune:90.
// Edit the body. Re-running manifest will not overwrite this file.

/** a hex colour for the user avatar */
// rune declares: [TYP] color: string
export type Color = string;
