// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber, IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a single board column
 * @internal
 */
// rune declares: [DTO] ColumnDto: id, label, wip
export class ColumnDto {
  /** a stable identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a stable identifier" })
  @IsString()
  id!: string;

  /** a short display label */
  // rune declares: [TYP] label: string
  @ApiProperty({ description: "a short display label" })
  @IsString()
  label!: string;

  /** a column work-in-progress limit */
  // rune declares: [TYP] wip: number
  @ApiProperty({ description: "a column work-in-progress limit" })
  @IsNumber()
  wip!: number;
}
