// Generated by rune manifest from board.rune:60.
// Edit the body. Re-running manifest will not overwrite this file.

/** number of comments on an issue */
// rune declares: [TYP] commentCount: number
export type CommentCount = number;
