// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a comment on an issue
 * @internal
 */
// rune declares: [DTO] CommentDto: id, author, bodyHtml, at
export class CommentDto {
  /** a stable identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a stable identifier" })
  @IsString()
  id!: string;

  /** the user id who wrote a comment */
  // rune declares: [TYP] author: string
  @ApiProperty({ description: "the user id who wrote a comment" })
  @IsString()
  author!: string;

  /** trusted, server-authored comment body HTML */
  // rune declares: [TYP] bodyHtml: string
  @ApiProperty({ description: "trusted, server-authored comment body HTML" })
  @IsString()
  bodyHtml!: string;

  /** an ISO 8601 timestamp */
  // rune declares: [TYP] at: string
  @ApiProperty({ description: "an ISO 8601 timestamp" })
  @IsString()
  at!: string;
}
