// Generated by rune manifest from board.rune:76.
// Edit the body. Re-running manifest will not overwrite this file.

/** completion ratio from 0 to 1 */
// rune declares: [TYP] completion: number
export type Completion = number;
