// Generated by rune manifest from board.rune:62.
// Edit the body. Re-running manifest will not overwrite this file.

/** ISO 8601 creation time */
// rune declares: [TYP] createdAt: string
export type CreatedAt = string;
