// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { IsArray, ValidateNested } from "class-validator";
import { ActivityDto } from "@/src/board/dto/activity.ts";
import { IssueDto } from "@/src/board/dto/issue.ts";
import { ProjectDto } from "@/src/board/dto/project.ts";
import { StatsDto } from "@/src/board/dto/stats.ts";

/**
 * the dashboard: stats, recent issues and recent activity
 * @internal
 */
// rune declares: [DTO] DashboardDto: project, stats, issue(s), activity(s)
export class DashboardDto {
  /** the project the board belongs to */
  @ValidateNested()
  @Type(() => ProjectDto)
  project!: ProjectDto;

  /** headline metrics for the dashboard */
  @ValidateNested()
  @Type(() => StatsDto)
  stats!: StatsDto;

  /** an issue card view-model */
  // rune: issue(s) — array of [DTO] IssueDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => IssueDto)
  issues!: IssueDto[];

  /** one entry in the recent-activity feed */
  // rune: activity(s) — array of [DTO] ActivityDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ActivityDto)
  activitys!: ActivityDto[];
}
