// Generated by rune manifest from board.rune:52.
// Edit the body. Re-running manifest will not overwrite this file.

/** trusted, server-authored issue description HTML */
// rune declares: [TYP] descriptionHtml: string
export type DescriptionHtml = string;
