// Generated by rune manifest from board.rune:74.
// Edit the body. Re-running manifest will not overwrite this file.

/** a one-line activity description */
// rune declares: [TYP] detail: string
export type Detail = string;
