// Generated by rune manifest from board.rune:82.
// Edit the body. Re-running manifest will not overwrite this file.

/** number of completed issues */
// rune declares: [TYP] done: number
export type Done = number;
