// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { IsArray, ValidateNested } from "class-validator";
import { ColumnDto } from "@/src/board/dto/column.ts";
import { IssueDto } from "@/src/board/dto/issue.ts";

/**
 * a column paired with its issues
 * @internal
 */
// rune declares: [DTO] GroupDto: column, issue(s)
export class GroupDto {
  /** a single board column */
  @ValidateNested()
  @Type(() => ColumnDto)
  column!: ColumnDto;

  /** an issue card view-model */
  // rune: issue(s) — array of [DTO] IssueDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => IssueDto)
  issues!: IssueDto[];
}
