// Generated by rune manifest from board.rune:28.
// Edit the body. Re-running manifest will not overwrite this file.

/** a stable identifier */
// rune declares: [TYP] id: string
export type Id = string;
