// Generated by rune manifest from board.rune:70.
// Edit the body. Re-running manifest will not overwrite this file.

/** an issue id used to fetch one issue */
// rune declares: [TYP:example=SPR-101] issueId: string
export type IssueId = string;
