// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { IsArray, ValidateNested } from "class-validator";
import { CommentDto } from "@/src/board/dto/comment.ts";
import { IssueDto } from "@/src/board/dto/issue.ts";
import { RelatedDto } from "@/src/board/dto/related.ts";
import { UserDto } from "@/src/board/dto/user.ts";

/**
 * a full issue page: the issue, assignees, comments and related issues
 * @internal
 */
// rune declares: [DTO] IssueDetailDto: issue, user(s), comment(s), related(s)
export class IssueDetailDto {
  /** an issue card view-model */
  @ValidateNested()
  @Type(() => IssueDto)
  issue!: IssueDto;

  /** a workspace member */
  // rune: user(s) — array of [DTO] UserDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => UserDto)
  users!: UserDto[];

  /** a comment on an issue */
  // rune: comment(s) — array of [DTO] CommentDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CommentDto)
  comments!: CommentDto[];

  /** a lean issue summary shown in the related list */
  // rune: related(s) — array of [DTO] RelatedDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => RelatedDto)
  relateds!: RelatedDto[];
}
