// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { IsArray, IsNumber, IsString, ValidateNested } from "class-validator";
import { ApiProperty } from "#api-doc";
import { TagDto } from "@/src/board/dto/tag.ts";

/**
 * an issue card view-model
 * @internal
 */
// rune declares: [DTO] IssueDto: id, title, status, priority, points, tag(s), assignee(s)
export class IssueDto {
  /** a stable identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a stable identifier" })
  @IsString()
  id!: string;

  /** an issue title */
  // rune declares: [TYP] title: string
  @ApiProperty({ description: "an issue title" })
  @IsString()
  title!: string;

  /** a workflow status (backlog, todo, in-progress, review, done) */
  // rune declares: [TYP] status: string
  @ApiProperty({ description: "a workflow status (backlog, todo, in-progress, review, done)" })
  @IsString()
  status!: string;

  /** an issue priority (low, medium, high, urgent) */
  // rune declares: [TYP] priority: string
  @ApiProperty({ description: "an issue priority (low, medium, high, urgent)" })
  @IsString()
  priority!: string;

  /** story points for an issue */
  // rune declares: [TYP] points: number
  @ApiProperty({ description: "story points for an issue" })
  @IsNumber()
  points!: number;

  /** a coloured label on an issue */
  // rune: tag(s) — array of [DTO] TagDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => TagDto)
  tags!: TagDto[];

  /** a user id assigned to an issue */
  // rune declares: [TYP] assignee: string
  // rune: assignee(s) — array of [TYP] assignee
  @ApiProperty({ description: "a user id assigned to an issue" })
  @IsArray()
  @IsString({ each: true })
  assignees!: string[];
}
