// Generated by rune manifest from board.rune:30.
// Edit the body. Re-running manifest will not overwrite this file.

/** a project key, e.g. SPR */
// rune declares: [TYP] key: string
export type Key = string;
