// Generated by rune manifest from board.rune:66.
// Edit the body. Re-running manifest will not overwrite this file.

/** an activity kind (comment, status, assign, create) */
// rune declares: [TYP] kind: string
export type Kind = string;
