// Generated by rune manifest from board.rune:36.
// Edit the body. Re-running manifest will not overwrite this file.

/** a short display label */
// rune declares: [TYP] label: string
export type Label = string;
