// Generated by rune manifest from board.rune:32.
// Edit the body. Re-running manifest will not overwrite this file.

/** a human-readable name */
// rune declares: [TYP] name: string
export type Name = string;
