// Generated by rune manifest from board.rune:46.
// Edit the body. Re-running manifest will not overwrite this file.

/** story points for an issue */
// rune declares: [TYP] points: number
export type Points = number;
