// Generated by rune manifest from board.rune:44.
// Edit the body. Re-running manifest will not overwrite this file.

/** an issue priority (low, medium, high, urgent) */
// rune declares: [TYP] priority: string
export type Priority = string;
