// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber, IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * the project the board belongs to
 * @internal
 */
// rune declares: [DTO] ProjectDto: id, key, name, velocity
export class ProjectDto {
  /** a stable identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a stable identifier" })
  @IsString()
  id!: string;

  /** a project key, e.g. SPR */
  // rune declares: [TYP] key: string
  @ApiProperty({ description: "a project key, e.g. SPR" })
  @IsString()
  key!: string;

  /** a human-readable name */
  // rune declares: [TYP] name: string
  @ApiProperty({ description: "a human-readable name" })
  @IsString()
  name!: string;

  /** points delivered per sprint */
  // rune declares: [TYP] velocity: number
  @ApiProperty({ description: "points delivered per sprint" })
  @IsNumber()
  velocity!: number;
}
