// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a lean issue summary shown in the related list
 * @internal
 */
// rune declares: [DTO] RelatedDto: id, title, status
export class RelatedDto {
  /** a stable identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a stable identifier" })
  @IsString()
  id!: string;

  /** an issue title */
  // rune declares: [TYP] title: string
  @ApiProperty({ description: "an issue title" })
  @IsString()
  title!: string;

  /** a workflow status (backlog, todo, in-progress, review, done) */
  // rune declares: [TYP] status: string
  @ApiProperty({ description: "a workflow status (backlog, todo, in-progress, review, done)" })
  @IsString()
  status!: string;
}
