// Generated by rune manifest from board.rune:88.
// Edit the body. Re-running manifest will not overwrite this file.

/** a workspace role (owner, maintainer, contributor) */
// rune declares: [TYP] role: string
export type Role = string;
