// Generated by rune manifest from board.rune:42.
// Edit the body. Re-running manifest will not overwrite this file.

/** a workflow status (backlog, todo, in-progress, review, done) */
// rune declares: [TYP] status: string
export type Status = string;
