// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsArray, IsNumber } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * headline metrics for the dashboard
 * @internal
 */
// rune declares: [DTO] StatsDto: total, done, completion, velocity, budget, trend(s)
export class StatsDto {
  /** total number of issues */
  // rune declares: [TYP] total: number
  @ApiProperty({ description: "total number of issues" })
  @IsNumber()
  total!: number;

  /** number of completed issues */
  // rune declares: [TYP] done: number
  @ApiProperty({ description: "number of completed issues" })
  @IsNumber()
  done!: number;

  /** completion ratio from 0 to 1 */
  // rune declares: [TYP] completion: number
  @ApiProperty({ description: "completion ratio from 0 to 1" })
  @IsNumber()
  completion!: number;

  /** points delivered per sprint */
  // rune declares: [TYP] velocity: number
  @ApiProperty({ description: "points delivered per sprint" })
  @IsNumber()
  velocity!: number;

  /** remaining budget in the project currency */
  // rune declares: [TYP] budget: number
  @ApiProperty({ description: "remaining budget in the project currency" })
  @IsNumber()
  budget!: number;

  /** completed points for one day of the trend */
  // rune declares: [TYP] trend: number
  // rune: trend(s) — array of [TYP] trend
  @ApiProperty({ description: "completed points for one day of the trend" })
  @IsArray()
  @IsNumber({}, { each: true })
  trends!: number[];
}
