// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a coloured label on an issue
 * @internal
 */
// rune declares: [DTO] TagDto: label, tone
export class TagDto {
  /** a short display label */
  // rune declares: [TYP] label: string
  @ApiProperty({ description: "a short display label" })
  @IsString()
  label!: string;

  /** a colour tone name for a tag chip */
  // rune declares: [TYP] tone: string
  @ApiProperty({ description: "a colour tone name for a tag chip" })
  @IsString()
  tone!: string;
}
