// Generated by rune manifest from board.rune:40.
// Edit the body. Re-running manifest will not overwrite this file.

/** an issue title */
// rune declares: [TYP] title: string
export type Title = string;
