// Generated by rune manifest from board.rune:48.
// Edit the body. Re-running manifest will not overwrite this file.

/** a colour tone name for a tag chip */
// rune declares: [TYP] tone: string
export type Tone = string;
