// Generated by rune manifest from board.rune:80.
// Edit the body. Re-running manifest will not overwrite this file.

/** total number of issues */
// rune declares: [TYP] total: number
export type Total = number;
