// Generated by rune manifest from board.rune:84.
// Edit the body. Re-running manifest will not overwrite this file.

/** completed points for one day of the trend */
// rune declares: [TYP] trend: number
export type Trend = number;
