// Generated by rune manifest from board.rune:64.
// Edit the body. Re-running manifest will not overwrite this file.

/** ISO 8601 last-updated time */
// rune declares: [TYP] updatedAt: string
export type UpdatedAt = string;
