// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { IsArray, ValidateNested } from "class-validator";
import { IssueDto } from "@/src/board/dto/issue.ts";
import { UserDto } from "@/src/board/dto/user.ts";

/**
 * a user profile: the user and their assigned issues
 * @internal
 */
// rune declares: [DTO] UserProfileDto: user, issue(s)
export class UserProfileDto {
  /** a workspace member */
  @ValidateNested()
  @Type(() => UserDto)
  user!: UserDto;

  /** an issue card view-model */
  // rune: issue(s) — array of [DTO] IssueDto
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => IssueDto)
  issues!: IssueDto[];
}
