// Generated by rune manifest from board.rune:72.
// Edit the body. Re-running manifest will not overwrite this file.

/** a user id used to fetch one profile */
// rune declares: [TYP:example=ada] userId: string
export type UserId = string;
