// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a workspace member
 * @internal
 */
// rune declares: [DTO] UserDto: id, name, bio, role, color
export class UserDto {
  /** a stable identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a stable identifier" })
  @IsString()
  id!: string;

  /** a human-readable name */
  // rune declares: [TYP] name: string
  @ApiProperty({ description: "a human-readable name" })
  @IsString()
  name!: string;

  /** a one-line user biography */
  // rune declares: [TYP] bio: string
  @ApiProperty({ description: "a one-line user biography" })
  @IsString()
  bio!: string;

  /** a workspace role (owner, maintainer, contributor) */
  // rune declares: [TYP] role: string
  @ApiProperty({ description: "a workspace role (owner, maintainer, contributor)" })
  @IsString()
  role!: string;

  /** a hex colour for the user avatar */
  // rune declares: [TYP] color: string
  @ApiProperty({ description: "a hex colour for the user avatar" })
  @IsString()
  color!: string;
}
