// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNotEmpty, IsString, MaxLength } from "class-validator";
import { Transform } from "class-transformer";
import { ApiProperty } from "#api-doc";

/**
 * a reference to one user by id
 * @internal
 */
// rune declares: [DTO] UserRefDto: userId
export class UserRefDto {
  /** a user id used to fetch one profile */
  // rune declares: [TYP:example=ada] userId: string
  @ApiProperty({ description: "a user id used to fetch one profile", example: "ada" })
  // Trim then require non-empty so empty/whitespace-only ids are rejected at the
  // validation seam (422) instead of falling through to the business lookup, and
  // bound the length so an unbounded id can't be reflected back in an error body.
  @Transform(({ value }) => (typeof value === "string" ? value.trim() : value))
  @IsString()
  @IsNotEmpty()
  @MaxLength(64)
  userId!: string;
}
