// Generated by rune manifest from board.rune:34.
// Edit the body. Re-running manifest will not overwrite this file.

/** points delivered per sprint */
// rune declares: [TYP] velocity: number
export type Velocity = number;
