// Generated by rune manifest from board.rune:38.
// Edit the body. Re-running manifest will not overwrite this file.

/** a column work-in-progress limit */
// rune declares: [TYP] wip: number
export type Wip = number;
