// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assertEquals } from "#std/assert";
import { Manifest } from "./mod.ts";
import { DiscoverResultDto } from "@/src/discovery/dto/discover-result.ts";

const sample = () =>
  ({
    entrys: [{ slug: "components__btn", label: "btn" }],
    problems: [{ kind: "case-json", path: "/x", detail: "boom" }],
  }) as unknown as DiscoverResultDto;

Deno.test("Manifest.fromDiscovery", () => {
  const m = new Manifest();
  // fromDiscovery stores the result and returns the instance for chaining.
  assertEquals(m.fromDiscovery(sample()) instanceof Manifest, true);
});

Deno.test("Manifest.toDto", () => {
  const dto = sample();
  const out = new Manifest().fromDiscovery(dto).toDto();
  assertEquals(out.entrys, dto.entrys);
  assertEquals(out.problems, dto.problems);
});
