// Generated by rune manifest from board.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { UserProfileDto } from "@/src/board/dto/user-profile.ts";
import { ISSUES, USERS } from "@/src/board/domain/business/board/mod.ts";

// a workspace member
export class User {
  /**
   * @param userId a user id used to fetch one profile
   * @returns a user profile: the user and their assigned issues
   */
  assemble(userId: string): UserProfileDto {
    const user = USERS.find((candidate) => candidate.id === userId);
    if (!user) throw new Error(`no user with id "${userId}"`);
    const issues = ISSUES.filter((issue) => issue.assignees.includes(userId));
    return { user, issues };
  }
}
