// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.
// User: a workspace member
import { assertEquals, assertThrows } from "#std/assert";
import { User } from "./mod.ts";

Deno.test("User.assemble — profile + the issues assigned to them", () => {
  const profile = new User().assemble("ada");
  assertEquals(profile.user.name, "Ada Lovelace");
  assertEquals(profile.issues.map((i) => i.id).sort(), ["SPR-101", "SPR-103"]);
});

Deno.test("User.assemble — unknown id throws", () => {
  assertThrows(() => new User().assemble("nobody"), Error, "nobody");
});
