// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assert, assertEquals, assertRejects } from "#std/assert";
import { Project } from "./mod.ts";

Deno.test("project — connectivity", async () => {
  // Scanning an empty dir reaches the fs boundary and returns a valid result.
  const dir = await Deno.makeTempDir();
  try {
    const r = await new Project().scan(dir);
    assert(Array.isArray(r.entrys));
    assert(Array.isArray(r.problems));
    assertEquals(r.entrys.length, 0);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("scan-failed", async () => {
  // A scanner that throws surfaces as the "scan-failed" fault slug.
  await assertRejects(
    () =>
      new Project().scan("/x", {
        discover: () => {
          throw new Error("disk on fire");
        },
      }),
    Error,
    "scan-failed",
  );
});
