// Generated by rune manifest from board.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.
//
// The board feature also owns the in-memory seed for this demo backend (no
// datastore). The sibling features (dashboard/issue/user) read these consts —
// a feature-to-feature read, not a data-adapter import. Lifted from the sprig
// fixture's BoardService/UserService.

import { BoardDto } from "@/src/board/dto/board.ts";
import { ProjectDto } from "@/src/board/dto/project.ts";
import { ColumnDto } from "@/src/board/dto/column.ts";
import { IssueDto } from "@/src/board/dto/issue.ts";
import { UserDto } from "@/src/board/dto/user.ts";
import { CommentDto } from "@/src/board/dto/comment.ts";
import { ActivityDto } from "@/src/board/dto/activity.ts";

export const PROJECT: ProjectDto = { id: "p1", key: "SPR", name: "sprig", velocity: 34 };

export const COLUMNS: ColumnDto[] = [
  { id: "backlog", label: "Backlog", wip: 0 },
  { id: "todo", label: "To do", wip: 8 },
  { id: "in-progress", label: "In progress", wip: 3 },
  { id: "review", label: "In review", wip: 4 },
  { id: "done", label: "Done", wip: 0 },
];

export const ISSUES: IssueDto[] = [
  {
    id: "SPR-101",
    title: "Compile template.html to a Preact render fn",
    status: "in-progress",
    priority: "urgent",
    points: 8,
    tags: [{ label: "compiler", tone: "violet" }, { label: "core", tone: "blue" }],
    assignees: ["ada", "alan"],
  },
  {
    id: "SPR-102",
    title: "Island prop bridge: serialize resolve() output",
    status: "review",
    priority: "high",
    points: 5,
    tags: [{ label: "ssr", tone: "green" }, { label: "core", tone: "blue" }],
    assignees: ["grace"],
  },
  {
    id: "SPR-103",
    title: "Navigation API soft-nav swaps only the outlet",
    status: "todo",
    priority: "high",
    points: 5,
    tags: [{ label: "router", tone: "amber" }],
    assignees: ["grace", "ada"],
  },
  {
    id: "SPR-104",
    title: "Named-outlet URL scheme (= segments)",
    status: "done",
    priority: "medium",
    points: 3,
    tags: [{ label: "router", tone: "amber" }, { label: "done", tone: "green" }],
    assignees: ["alan"],
  },
  {
    id: "SPR-105",
    title: "Scoped styles via a CSS-modules esbuild plugin",
    status: "backlog",
    priority: "low",
    points: 2,
    tags: [{ label: "build", tone: "slate" }],
    assignees: [],
  },
  {
    id: "SPR-106",
    title: "Dev live-reload over SSE",
    status: "todo",
    priority: "medium",
    points: 3,
    tags: [{ label: "dx", tone: "blue" }],
    assignees: ["grace"],
  },
];

export const USERS: UserDto[] = [
  { id: "ada", name: "Ada Lovelace", bio: "Wrote the first algorithm intended for a machine.", role: "owner", color: "#7c3aed" },
  { id: "alan", name: "Alan Turing", bio: "Formalised computation and the Turing machine.", role: "maintainer", color: "#2563eb" },
  { id: "grace", name: "Grace Hopper", bio: "Pioneered machine-independent programming languages.", role: "maintainer", color: "#059669" },
];

export const COMMENTS: Record<string, CommentDto[]> = {
  "SPR-101": [
    { id: "c1", author: "alan", bodyHtml: "<p>Hoisted the binding compiler — review the track path.</p>", at: "2026-06-17T10:00:00Z" },
    { id: "c2", author: "ada", bodyHtml: "<p>Nice. Watch the safe-nav case in member chains.</p>", at: "2026-06-18T08:30:00Z" },
  ],
  "SPR-104": [
    { id: "c3", author: "alan", bodyHtml: "<p>Canonical sort makes back/forward stable.</p>", at: "2026-06-12T16:00:00Z" },
  ],
};

export const ACTIVITY: ActivityDto[] = [
  { id: "a1", kind: "status", actor: "ada", issueId: "SPR-101", at: "2026-06-19T14:12:00Z", detail: "moved to In progress" },
  { id: "a2", kind: "comment", actor: "ada", issueId: "SPR-101", at: "2026-06-18T08:30:00Z", detail: "commented" },
  { id: "a3", kind: "assign", actor: "grace", issueId: "SPR-102", at: "2026-06-19T08:45:00Z", detail: "self-assigned" },
  { id: "a4", kind: "create", actor: "grace", issueId: "SPR-106", at: "2026-06-11T13:30:00Z", detail: "created the issue" },
  { id: "a5", kind: "status", actor: "alan", issueId: "SPR-104", at: "2026-06-12T16:20:00Z", detail: "moved to Done" },
];

// the kanban board aggregate
export class Board {
  /**
   * @returns the whole board: a project and its grouped issues
   */
  assemble(): BoardDto {
    const groups = COLUMNS.map((column) => ({
      column,
      issues: ISSUES.filter((issue) => issue.status === column.id),
    }));
    return { project: PROJECT, groups };
  }
}
