// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.
// Board: the kanban board aggregate
import { assertEquals } from "#std/assert";
import { Board } from "./mod.ts";

Deno.test("Board.assemble — project + 5 column groups, issues grouped by status", () => {
  const board = new Board().assemble();
  assertEquals(board.project.name, "sprig");
  assertEquals(board.groups.length, 5);
  // grouped by status: in-progress holds SPR-101, done holds SPR-104
  assertEquals(board.groups.find((g) => g.column.id === "in-progress")?.issues.map((i) => i.id), ["SPR-101"]);
  assertEquals(board.groups.find((g) => g.column.id === "done")?.issues.map((i) => i.id), ["SPR-104"]);
  // every seed issue lands in exactly one group
  assertEquals(board.groups.reduce((n, g) => n + g.issues.length, 0), 6);
});
