#!/usr/bin/env -S deno run -A
// `sprig build` (M7 — per-island code-split). For each island (a folder with
// template.html + logic.ts) it serializes the template → JSON AST and generates a
// tiny entry `isl.<sel>.ts` that imports just that island's logic + AST and calls
// registerIsland(). It also generates the eager loader `client.ts`. All entries are
// bundled in ONE `deno bundle --code-splitting` pass, so esbuild dedups the shared
// runtime (@sprig/core + interpreter + hydrate) into a single content-hashed chunk
// referenced by every entry — never duplicated. Output:
//   <out>/client.js          the eager loader (scans DOM, lazy-loads islands by trigger)
//   <out>/isl.<sel>.js       one tiny chunk per island (dynamic-imported on its trigger)
//   <out>/chunk-<hash>.js    the shared runtime, loaded once
// The ?v= cache-bust is the content hash of <out>/ recomputed by the SSR on demand
// (mod.ts readVersion) — no manifest file is written; the build is self-contained in <out>.
import { basename, dirname, fromFileUrl, join, relative } from "@std/path";
import { walk } from "@std/fs/walk";
import { parseTemplate } from "./parse.ts";
import { serialize } from "./serialize.ts";
import { componentScopeId, scopeCss } from "./scope.ts";
import { assertStaticPage } from "./mod.ts";
import { shortHash } from "./hash.ts";

export interface BuildResult {
  islands: string[];
  chunks: string[];
  out: string;
  bytes: number;
  hash: string;
}

export async function buildClient(srcDir: string, outDir: string, opts: { dev?: boolean } = {}): Promise<BuildResult> {
  const here = dirname(fromFileUrl(import.meta.url));
  const hydratePath = join(here, "hydrate.ts");
  const hmrPath = join(here, "hmr.ts");
  const genDir = join(outDir, ".gen");
  const dev = !!opts.dev;

  // 1. discover islands + serialize their templates. Islands register/hydrate by
  //    SELECTOR (the client matches <sprig-island data-sel="…">), so two islands
  //    that share a basename cannot both be wired up — that collapsed silently to a
  //    single isl.<sel>.ts before. Detect it and fail loudly (like assertStaticPage).
  const islands: Array<{ sel: string; logic: string; tpl: string; scope: string }> = [];
  // static (non-island) components shipped to the client so an island's in-browser
  // re-render can compose them (keyed by selector; page roots are excluded).
  const statics = new Map<string, { sel: string; tpl: string; scope: string }>();
  // every component's serialized template, keyed by relDir — emitted to templates.json
  // so the SSR renders prebuilt ASTs and never runs tree-sitter at runtime.
  const templates: Record<string, unknown> = {};
  const seen = new Map<string, string>(); // selector → relDir of the first island
  for await (const entry of walk(srcDir, { includeDirs: false, match: [/template\.html$/] })) {
    const dir = dirname(entry.path);
    await assertStaticPage(dir); // a pages/<name>/ folder cannot be an island
    const sel = basename(dir);
    const relDir = relative(srcDir, dir).replace(/\\/g, "/");
    // parse + serialize ONCE (the only place tree-sitter runs); record for the SSR registry.
    const ast = serialize(await parseTemplate(await Deno.readTextFile(entry.path)));
    templates[relDir] = ast;
    const tpl = JSON.stringify(ast);
    const logic = join(dir, "logic.ts");
    if (!(await fileExists(logic))) {
      // not an island → a static component. Ship its template to the client registry
      // UNLESS it's a routed page root (a page isn't embedded as a child of an island).
      if (!isPageRoot(relDir)) statics.set(sel, { sel, tpl, scope: componentScopeId(relDir) });
      continue;
    }
    const prev = seen.get(sel);
    if (prev) {
      throw new Error(
        `sprig build: duplicate island selector "${sel}" — both "${prev}" and "${relDir}" ` +
          `are islands sharing the basename "${sel}". Islands register/hydrate by selector, ` +
          `so they cannot share a name. Rename one folder.`,
      );
    }
    seen.set(sel, relDir);
    islands.push({ sel, logic, tpl, scope: componentScopeId(relDir) });
  }

  // 2. generate entries (the loader + one per island). In dev the loader also starts
  //    the HMR client, and island chunks FETCH their AST (so a hard reload is fresh)
  //    instead of baking it in.
  await Deno.mkdir(genDir, { recursive: true });
  await Deno.writeTextFile(
    join(genDir, "client.ts"),
    [
      `// GENERATED by sprig build — the eager loader.`,
      `import { bootstrapIslands, registerComponent, setupSoftNav, type SprigConfig } from ${q(hydratePath)};`,
      ...(dev ? [`import { startHmr } from ${q(hmrPath)};`] : []),
      `const cfg = JSON.parse(document.getElementById("__sprig_config")?.textContent ?? "{}") as SprigConfig;`,
      ...(dev ? [`startHmr(cfg.base);`] : []),
      // register static component templates so islands can compose them on the client
      ...[...statics.values()].map((s) =>
        `registerComponent(${JSON.stringify(s.sel)}, { template: ${s.tpl}, scope: ${JSON.stringify(s.scope)} });`
      ),
      `const run = () => { bootstrapIslands(cfg); setupSoftNav(cfg); };`,
      `if (document.readyState === "loading") addEventListener("DOMContentLoaded", run); else run();`,
      ``,
    ].join("\n"),
  );
  for (const isl of islands) {
    const lines = dev
      ? [
        `// GENERATED by sprig build (dev) — the ${isl.sel} island chunk (fetches its AST).`,
        `import { registerIsland, makeClassSetup, fetchAst } from ${q(hydratePath)};`,
        `import logic from ${q(isl.logic)};`,
        // a class default-export has no .setup → adapt it; { setup } objects use .setup
        `const __setup = logic.setup ?? makeClassSetup(logic);`,
        `const __cfg = JSON.parse(document.getElementById("__sprig_config")?.textContent ?? "{}");`,
        `fetchAst(__cfg.base ?? "/ui", ${JSON.stringify(isl.sel)}).then((t) =>`,
        `  registerIsland(${JSON.stringify(isl.sel)}, { setup: __setup, template: t, scope: ${JSON.stringify(isl.scope)} }));`,
        ``,
      ]
      : [
        `// GENERATED by sprig build — the ${isl.sel} island chunk.`,
        `import { registerIsland, makeClassSetup } from ${q(hydratePath)};`,
        `import logic from ${q(isl.logic)};`,
        `const __setup = logic.setup ?? makeClassSetup(logic);`,
        `registerIsland(${JSON.stringify(isl.sel)}, { setup: __setup, template: ${isl.tpl}, scope: ${JSON.stringify(isl.scope)} });`,
        ``,
      ];
    await Deno.writeTextFile(join(genDir, `isl.${isl.sel}.ts`), lines.join("\n"));
  }

  // 3. clean stale JS, then bundle ALL entries with code-splitting
  await Deno.mkdir(outDir, { recursive: true });
  for await (const e of Deno.readDir(outDir)) {
    if (e.isFile && (e.name.endsWith(".js") || e.name.endsWith(".js.map"))) {
      await Deno.remove(join(outDir, e.name));
    }
  }
  const entries = [join(genDir, "client.ts"), ...islands.map((i) => join(genDir, `isl.${i.sel}.ts`))];
  const res = await new Deno.Command("deno", {
    args: ["bundle", "--platform", "browser", "--minify", "--code-splitting", "--outdir", outDir, ...entries],
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!res.success) {
    throw new Error("client bundle failed:\n" + new TextDecoder().decode(res.stderr));
  }
  await Deno.remove(genDir, { recursive: true }).catch(() => {});

  // 4. per-component styles.css → scoped (view encapsulation) → Tailwind → app.css
  await buildCss(srcDir, outDir);

  // 4b. the SSR registry: every component's serialized template, keyed by relDir, so the
  //     server renders prebuilt ASTs and never loads the wasm parser at runtime.
  await Deno.writeTextFile(join(outDir, "templates.json"), JSON.stringify(templates));

  // 5. collect outputs (.js + app.css) + hash them for the ?v= cache-bust
  const files: string[] = [];
  let total = 0;
  for await (const e of Deno.readDir(outDir)) {
    if (e.isFile && (e.name.endsWith(".js") || e.name === "app.css")) {
      files.push(e.name);
      total += (await Deno.stat(join(outDir, e.name))).size;
    }
  }
  const chunks = files.filter((f) => f.startsWith("chunk-")).sort();
  // The cache-bust version is the static dir's content hash — the SSR recomputes it on
  // demand (mod.ts readVersion), so the build leaves NO manifest file beside static/;
  // everything the build produces lives inside the one output folder.
  const hash = await shortHash(files.slice().sort().map((f) => join(outDir, f)));
  return { islands: islands.map((i) => i.sel), chunks, out: join(outDir, "client.js"), bytes: total, hash };
}

/** Collect each component's styles.css, scope it for view encapsulation, then run
 *  Tailwind (expands @apply + emits utilities scanned from the templates) → app.css. */
export async function buildCss(srcDir: string, outDir: string): Promise<void> {
  const parts: string[] = [];
  for await (const entry of walk(srcDir, { includeDirs: false, match: [/styles\.css$/] })) {
    const dir = dirname(entry.path);
    const relDir = relative(srcDir, dir).replace(/\\/g, "/");
    const css = await Deno.readTextFile(entry.path);
    // scope by the component's UNIQUE path (matches mod.ts's componentScopeId) so two
    // same-basename folders never share a scope attr → no cross-folder CSS leak.
    parts.push(`/* ${relDir} (scoped) */\n${scopeCss(css, componentScopeId(relDir))}`);
  }
  // Run the Tailwind CLI from a persistent cache dir OUTSIDE the repo: it needs its
  // own deno.json (nodeModulesDir:auto) to resolve `@import "tailwindcss"`, but a
  // deno.json inside the workspace trips Deno's "config must be a workspace member"
  // check. Outside the repo, node_modules persists across builds (fast after first).
  const home = Deno.env.get("HOME") || Deno.env.get("TMPDIR") || "/tmp";
  const twDir = join(home, ".cache", "sprig-tailwind");
  await Deno.mkdir(twDir, { recursive: true });
  await Deno.writeTextFile(
    join(twDir, "deno.json"),
    JSON.stringify({
      nodeModulesDir: "auto",
      imports: { "@tailwindcss/cli": "npm:@tailwindcss/cli@^4", "tailwindcss": "npm:tailwindcss@^4" },
    }),
  );
  const input = `@import "tailwindcss";\n@source "${srcDir}/**/*.html";\n\n${parts.join("\n\n")}\n`;
  await Deno.writeTextFile(join(twDir, "input.css"), input);
  const res = await new Deno.Command("deno", {
    args: [
      "run", "-A", "--node-modules-dir=auto",
      "npm:@tailwindcss/cli@^4", "-i", join(twDir, "input.css"), "-o", join(outDir, "app.css"), "--minify",
    ],
    cwd: twDir,
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!res.success) {
    throw new Error("tailwind css build failed:\n" + new TextDecoder().decode(res.stderr));
  }
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await Deno.stat(p);
    return true;
  } catch {
    return false;
  }
}

/** A routed page root (pages/<page>/ or pages/_preview/<id>/) — NOT a page-local
 *  component (pages/<page>/components/<x>/). Page roots aren't embedded as children
 *  of islands, so their templates aren't shipped to the client registry. */
function isPageRoot(relDir: string): boolean {
  const parts = relDir.split("/");
  return parts[0] === "pages" && parts[parts.length - 2] !== "components";
}
function q(s: string): string {
  return JSON.stringify(s);
}

if (import.meta.main) {
  const here = dirname(fromFileUrl(import.meta.url));
  const srcDir = join(here, "../../src"); // ui/src
  const outDir = join(Deno.cwd(), "static");
  const dev = Deno.args.includes("--dev");
  const r = await buildClient(srcDir, outDir, { dev });
  console.log(
    `sprig build${dev ? " (dev/HMR)" : ""}: ${r.islands.length} island chunk(s) [${r.islands.join(", ")}] + ` +
      `${r.chunks.length} shared chunk(s) → ${outDir} (${(r.bytes / 1024).toFixed(1)}kb total, v=${r.hash})`,
  );
}
