// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// stage background behind the component
// rune declares: [TYP] background: string
export type Background = string;
