// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// gallery group + URL segment
// rune declares: [TYP] category: string
export type Category = string;
