// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// resolved .tsx file for the component (or "")
// rune declares: [TYP] componentFile: string
export type ComponentFile = string;
