// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// top-level control widget definitions, keyed by prop name
// rune declares: [TYP] controlDefs: Record<string, unknown>
export type ControlDefs = Record<string, unknown>;
