// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// absolute path to the component directory
// rune declares: [TYP] dir: string
export type Dir = string;
