// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// PascalCase export expected from componentFile
// rune declares: [TYP] exportName: string
export type ExportName = string;
