// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// absolute file path
// rune declares: [TYP] file: string
export type File = string;
