// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// optional sub-group + URL segment ("" when absent)
// rune declares: [TYP] folder: string
export type Folder = string;
