// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// children via dangerouslySetInnerHTML
// rune declares: [TYP] innerHtml: string
export type InnerHtml = string;
