// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// absolute path to the isolate/ folder
// rune declares: [TYP] isolateDir: string
export type IsolateDir = string;
