// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// absolute path to the case JSON file
// rune declares: [TYP] jsonPath: string
export type JsonPath = string;
