// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// "static" or "island"
// rune declares: [TYP] kind: string
export type Kind = string;
