// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// human label (the folder name)
// rune declares: [TYP] label: string
export type Label = string;
