// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { IsArray, ValidateNested } from "class-validator";
import { EntryDto } from "@/src/discovery/dto/entry.ts";
import { ProblemDto } from "@/src/discovery/dto/problem.ts";

// the gallery view model derived from discovery
export class ManifestDto {
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => EntryDto)
  entrys!: EntryDto[];

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ProblemDto)
  problems!: ProblemDto[];
}
