// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// sub-component mock/force directives, keyed by name
// rune declares: [TYP] mocks: Record<string, unknown>
export type Mocks = Record<string, unknown>;
