// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a case or test name
// rune declares: [TYP] name: string
export type Name = string;
