// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the offending file or directory for a problem
// rune declares: [TYP] path: string
export type Path = string;
