// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a discovery config problem (fixture/case/file/export)
export class ProblemDto {
  @IsString()
  kind!: string;

  @IsString()
  path!: string;

  @IsString()
  detail!: string;
}
