// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// bare-key props passed to the component
// rune declares: [TYP] props: Record<string, unknown>
export type Props = Record<string, unknown>;
