// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

// the host project root to scan
export class RootDto {
  @ApiProperty({ example: "." })
  @IsString()
  projectRoot!: string;
}
