// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// preview route, e.g. /components/buttons/primary
// rune declares: [TYP] route: string
export type Route = string;
