// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// signal-typed values, keyed by name
// rune declares: [TYP] signals: Record<string, unknown>
export type Signals = Record<string, unknown>;
