// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// root-qualified id, e.g. islands__counter
// rune declares: [TYP] slug: string
export type Slug = string;
