// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// source root: components, islands, or pages
// rune declares: [TYP] sourceRoot: string
export type SourceRoot = string;
