// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// per-sub-component control defs, keyed by function name
// rune declares: [TYP] subControlDefs: Record<string, unknown>
export type SubControlDefs = Record<string, unknown>;
