// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// "component" or "page"
// rune declares: [TYP] target: string
export type Target = string;
