// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a Playwright spec belonging to a case
export class TestDto {
  @IsString()
  name!: string;

  @IsString()
  file!: string;
}
