// Generate sprig preview pages from a discovery manifest — the sprig-native
// replacement for materialize.ts. For each discovered case it generates a static
// preview page that renders the target component DIRECTLY plus the shared
// <stage-bridge> island (the bridge can't host the target as a child on the client,
// so they are siblings). The target component is copied into
// app/src/_preview/targets/<alias>/ with a dash-cased selector (`x-<name>`) so it
// never shadows a native element like <button>. A manifest.gen.ts of
// { routes, modules } is spread into app/src/main.ts. The app then builds (islands
// code-split) and serves under one serveSprig origin — no Vite, no Fresh.
import { join } from "#std/path";
import { ensureDir, exists } from "#std/fs";
import type { CaseDef, ComponentEntry } from "../../server/src/core/business/discover/mod.ts";

const sanitize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

/** Render a JS value as a sprig template expression literal (strings single-quoted). */
function lit(v: unknown): string {
  if (typeof v === "string") return `'${v.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  if (v == null) return "null";
  return `'${JSON.stringify(v).replace(/'/g, "\\'")}'`;
}

/** The target tag for a case: literal input bindings from the case's props (static
 *  components) + the innerHtml as `content`. Island signals are applied by the bridge,
 *  so island targets get no input bindings. */
function targetTag(alias: string, e: ComponentEntry, c: CaseDef): string {
  const attrs: string[] = [];
  if (e.kind !== "island") {
    for (const [k, v] of Object.entries(c.props)) attrs.push(`[${k}]="${lit(v)}"`);
    if (typeof c.innerHtml === "string") attrs.push(`[content]="${lit(c.innerHtml)}"`);
  }
  return `<${alias} ${attrs.join(" ")}></${alias}>`.replace(/\s+>/, ">");
}

export async function generatePreviews(entries: ComponentEntry[], appSrcDir: string): Promise<number> {
  const previewPagesDir = join(appSrcDir, "pages", "_preview");
  const targetsDir = join(appSrcDir, "_preview", "targets");
  for (const d of [previewPagesDir, join(appSrcDir, "_preview")]) {
    if (await exists(d)) await Deno.remove(d, { recursive: true });
  }
  await ensureDir(previewPagesDir);
  await ensureDir(targetsDir);

  const routes: { path: string; load: string }[] = [];
  const moduleLines: string[] = [];
  let pages = 0;

  for (const e of entries) {
    const alias = "x-" + sanitize(e.label); // dash-cased → never shadows a native element

    // copy the target folder-component (template + styles + logic)
    const tDir = join(targetsDir, alias);
    await ensureDir(tDir);
    await Deno.copyFile(join(e.dir, "template.html"), join(tDir, "template.html"));
    if (await exists(join(e.dir, "styles.css"))) {
      await Deno.copyFile(join(e.dir, "styles.css"), join(tDir, "styles.css"));
    }
    if (e.kind === "island" && (await exists(join(e.dir, "logic.ts")))) {
      await Deno.copyFile(join(e.dir, "logic.ts"), join(tDir, "logic.ts"));
    }

    const meta = { name: e.label, selector: alias, background: e.background, controlDefs: e.controlDefs };

    for (const c of e.cases) {
      const pageId = "pv-" + sanitize(e.slug) + "-" + sanitize(c.name);
      const pDir = join(previewPagesDir, pageId);
      await ensureDir(pDir);
      // the target rendered directly + the bridge as a sibling
      await Deno.writeTextFile(
        join(pDir, "template.html"),
        `<div class="iso-stage-page">\n  ${targetTag(alias, e, c)}\n  ` +
          `<stage-bridge [meta]="meta" [case]="case"></stage-bridge>\n</div>\n`,
      );
      const caseData = { props: c.props, signals: c.signals ?? {}, innerHtml: c.innerHtml ?? null };
      routes.push({ path: c.route.replace(/^\//, ""), load: `./pages/_preview/${pageId}` });
      moduleLines.push(
        `  ${JSON.stringify("./pages/_preview/" + pageId)}: { resolve: () => (${JSON.stringify({ meta, case: caseData })}) },`,
      );
      pages++;
    }
  }

  const manifest = [
    `// GENERATED by isolate — sprig preview routes + resolvers. Do not edit.`,
    `import type { Route } from "@sprig/core";`,
    ``,
    `export const routes: Route[] = ${JSON.stringify(routes, null, 0)};`,
    ``,
    `// deno-lint-ignore-file no-explicit-any`,
    `export const modules: Record<string, { resolve: () => any }> = {`,
    ...moduleLines,
    `};`,
    ``,
  ].join("\n");
  await Deno.writeTextFile(join(previewPagesDir, "manifest.gen.ts"), manifest);
  return pages;
}
