// Generated by rune manifest from board.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { IssueDetailDto } from "@/src/board/dto/issue-detail.ts";
import { COMMENTS, ISSUES, USERS } from "@/src/board/domain/business/board/mod.ts";
import { HttpException } from "jsr:@danet/core@2";

// a single unit of work
export class Issue {
  /**
   * @param issueId an issue id used to fetch one issue
   * @returns a full issue page: the issue, assignees, comments and related issues
   */
  assemble(issueId: string): IssueDetailDto {
    const issue = ISSUES.find((candidate) => candidate.id === issueId);
    // A well-formed id that names no issue is a client addressing error, not a
    // server fault: signal 404 (NotFoundException) with a generic message that
    // does NOT echo the raw, unbounded id back to the client.
    if (!issue) throw new HttpException(404, "no such issue");
    const users = USERS.filter((user) => issue.assignees.includes(user.id));
    const comments = COMMENTS[issueId] ?? [];
    // Rank candidates by actual relevance to the subject issue (shared tags,
    // then same status), so "relateds" reflects a real relationship rather than
    // the first three seed issues. Ties keep seed order for determinism.
    const subjectTags = new Set(issue.tags.map((tag) => tag.label));
    const relateds = ISSUES
      .filter((candidate) => candidate.id !== issueId)
      .map((candidate) => {
        const sharedTags =
          candidate.tags.filter((tag) => subjectTags.has(tag.label)).length;
        const sameStatus = candidate.status === issue.status ? 1 : 0;
        return { candidate, score: sharedTags * 2 + sameStatus };
      })
      .sort((a, b) => b.score - a.score)
      .slice(0, 3)
      .map(({ candidate }) => ({
        id: candidate.id,
        title: candidate.title,
        status: candidate.status,
      }));
    return { issue, users, comments, relateds };
  }
}
