// Generated by rune manifest from board.rune.
// Edit the body. Re-running manifest will not overwrite this file.
// Issue: a single unit of work
import { assertEquals, assertThrows } from "#std/assert";
import { Issue } from "./mod.ts";

Deno.test("Issue.assemble — issue + assignees + comments + ≤3 relateds", () => {
  const detail = new Issue().assemble("SPR-101");
  assertEquals(detail.issue.id, "SPR-101");
  assertEquals(detail.users.map((u) => u.id), ["ada", "alan"]); // resolved from assignees
  assertEquals(detail.comments.length, 2);
  assertEquals(detail.relateds.length, 3);
  assertEquals(detail.relateds.some((r) => r.id === "SPR-101"), false); // self excluded
});

Deno.test("Issue.assemble — unknown id throws", () => {
  // A well-formed id that names no issue is a client addressing error: it must
  // throw (mapped to 404), but the generic message must NOT echo the raw id
  // back to the client (info-reflection leak — see bugs #19/#50).
  const err = assertThrows(
    () => new Issue().assemble("NOPE"),
    Error,
    "no such issue",
  );
  assertEquals((err as Error).message.includes("NOPE"), false);
});
